// <auto-generated />
using System;
using FleetRent.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetRent.Infrastructure.Migrations
{
    [DbContext(typeof(FleetRentDbContext))]
    partial class FleetRentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetRent.Domain.Entities.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14da2f03-4a6b-4a9f-8f82-450a7e8262fb"),
                            Identifier = "Bike001",
                            Model = "Bike Sport",
                            Plate = "ABC1D23",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("e8f980e0-1209-47a1-8097-819680973882"),
                            Identifier = "Bike002",
                            Model = "Bike E",
                            Plate = "ABC1C34",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("d9b341e8-88f6-4d6b-b684-7a6c262dab89"),
                            Identifier = "Bike003",
                            Model = "Bike Pop",
                            Plate = "XYZ1C38",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("FleetRent.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LicenseImagePath")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee813936-8f43-4a96-a05e-f0b3f5e0a876"),
                            BirthDate = new DateOnly(1990, 5, 15),
                            Cnpj = "11222333000144",
                            Identifier = "JS1990",
                            LicenseNumber = "01234567890",
                            LicenseType = "A",
                            Name = "João da Silva"
                        },
                        new
                        {
                            Id = new Guid("4f5d5e1a-f761-4c60-8f9f-6a7e0a8d6b9c"),
                            BirthDate = new DateOnly(1985, 10, 2),
                            Cnpj = "5552333000144",
                            Identifier = "MO1985",
                            LicenseNumber = "09876543211",
                            LicenseType = "B",
                            Name = "Maria Oliveira"
                        },
                        new
                        {
                            Id = new Guid("b1a6a3a1-7c9c-4f8e-8a0b-9d6c1b3f5e2d"),
                            BirthDate = new DateOnly(1978, 1, 30),
                            Cnpj = "5552845000144",
                            Identifier = "CP1978",
                            LicenseNumber = "05566778899",
                            LicenseType = "AB",
                            Name = "Carlos Pereira"
                        });
                });

            modelBuilder.Entity("FleetRent.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<string>("BikeIdentifier")
                        .HasColumnType("text");

                    b.Property<int>("BikeYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FleetRent.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<DateTime>("PlannedEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("DriverId");

                    b.ToTable("Rentals", (string)null);
                });

            modelBuilder.Entity("FleetRent.Domain.Entities.Rental", b =>
                {
                    b.HasOne("FleetRent.Domain.Entities.Bike", "Bike")
                        .WithMany("Rentals")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetRent.Domain.Entities.Driver", "Driver")
                        .WithMany("Rentals")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FleetRent.Domain.ValueObjects.RentalPlan", "Plan", b1 =>
                        {
                            b1.Property<Guid>("RentalId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("DailyRate")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("PlanDailyRate");

                            b1.Property<int>("Days")
                                .HasColumnType("integer")
                                .HasColumnName("PlanDays");

                            b1.Property<decimal>("EarlyReturnFinePercentage")
                                .HasColumnType("numeric(5,4)")
                                .HasColumnName("PlanEarlyReturnFine");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PlanType");

                            b1.HasKey("RentalId");

                            b1.ToTable("Rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalId");
                        });

                    b.Navigation("Bike");

                    b.Navigation("Driver");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("FleetRent.Domain.Entities.Bike", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("FleetRent.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
